import os
from typing import Dict, Any, Optional
from fpdf import FPDF
from app.core.config import settings


def sanitize_text(text: Any) -> str:
    """Sanitizes text to prevent unicode/encoding and formatting errors in standard PDF fonts."""
    if text is None:
        return ""
    s = str(text)
    # Replace non-latin1 unicode characters with ascii equivalents
    s = s.replace("—", "-").replace("–", "-").replace("“", '"').replace("”", '"').replace("’", "'").replace("‘", "'")
    s = s.replace("•", "*").replace("✓", "+").replace("✕", "x").replace("…", "...").replace("₹", "INR")
    # Encode to latin-1 safe representation
    return s.encode("latin-1", "replace").decode("latin-1")


class InterviewReportPDF(FPDF):
    def header(self):
        self.set_x(10)
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(30, 41, 59)
        self.cell(190, 10, "ARDHNARISHWAR UNIVERSAL AI INTERVIEW REPORT", ln=True, align="C")
        self.set_x(10)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(100, 116, 139)
        self.cell(190, 5, "Multi-Field Assessment, Competency Analysis & Focus Recommendations", ln=True, align="C")
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_x(10)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(148, 163, 184)
        self.cell(190, 10, f"Page {self.page_no()} | Generated by Ardhnarishwar AI SaaS Engine", align="C")


class ReportGenerator:
    def generate_pdf_report(
        self,
        candidate_data: Dict[str, Any],
        job_data: Dict[str, Any],
        evaluation_data: Dict[str, Any],
        company_name: str,
        output_path: str
    ) -> str:
        pdf = InterviewReportPDF(orientation="P", unit="mm", format="A4")
        pdf.set_left_margin(10)
        pdf.set_right_margin(10)
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)

        field_name = sanitize_text(evaluation_data.get("field_name", "Universal"))
        target_role = sanitize_text(evaluation_data.get("target_role", job_data.get("title", "Specialist")))
        cand_name = sanitize_text(candidate_data.get("name", "Candidate"))
        cand_email = sanitize_text(candidate_data.get("email", "N/A"))
        comp_name = sanitize_text(company_name or "Ardhnarishwar AI SaaS")

        # 1. Overview Table
        pdf.set_x(10)
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(190, 7, f"Candidate: {cand_name} ({cand_email})", ln=True)
        
        pdf.set_x(10)
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(190, 6, f"Company: {comp_name} | Professional Field: {field_name} | Role: {target_role}", ln=True)
        pdf.ln(3)

        # 2. Overall Score Banner
        pdf.set_x(10)
        current_y = pdf.get_y()
        pdf.set_fill_color(241, 245, 249)
        pdf.rect(10, current_y, 190, 22, "F")
        pdf.set_y(current_y + 3)

        pdf.set_x(14)
        pdf.set_font("Helvetica", "B", 12)
        overall = evaluation_data.get("overall_score", 0.0)
        rec = sanitize_text(str(evaluation_data.get("recommendation", "CONSIDER")).replace("_", " "))
        pdf.cell(90, 6, f"Overall Competency Score: {overall} / 100", align="L")
        pdf.cell(90, 6, f"AI Recommendation: {rec}", align="R", ln=True)

        pdf.set_x(14)
        pdf.set_font("Helvetica", "", 8.5)
        pdf.set_text_color(100, 116, 139)
        engine_v = sanitize_text(evaluation_data.get("engine_version", "universal-v1.0"))
        conf = int(evaluation_data.get("confidence_indicator", 0.92) * 100)
        pdf.cell(180, 5, f"Engine: {engine_v} | AI Confidence: {conf}% | Zero External LLM Dependency", ln=True)
        pdf.set_text_color(15, 23, 42)
        pdf.ln(6)

        # 3. Sub-scores Breakdown
        pdf.set_x(10)
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(190, 7, "Core Competency Matrix", ln=True)
        pdf.set_font("Helvetica", "", 9.5)

        pdf.set_x(10)
        pdf.cell(47, 6, f"Domain/Tech: {evaluation_data.get('technical_score', 0)}%")
        pdf.cell(47, 6, f"Problem Solving: {evaluation_data.get('problem_solving_score', 0)}%")
        pdf.cell(47, 6, f"Communication: {evaluation_data.get('communication_score', 0)}%")
        pdf.cell(47, 6, f"Behavioral: {evaluation_data.get('behavioral_score', 0)}%", ln=True)
        pdf.ln(4)

        # 4. Strengths
        pdf.set_x(10)
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(190, 7, "Demonstrated Strengths", ln=True)
        pdf.set_font("Helvetica", "", 9)
        for s in evaluation_data.get("strengths", [])[:4]:
            pdf.set_x(10)
            pdf.cell(190, 5, sanitize_text(f"+ {s}"), ln=True)
        pdf.ln(3)

        # 5. Focus Areas & Actionable Suggestions
        pdf.set_x(10)
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(190, 7, sanitize_text(f"Key Focus Areas & Improvement Guidance for {field_name}"), ln=True)
        pdf.set_font("Helvetica", "", 9)
        for sug in evaluation_data.get("improvement_suggestions", [])[:3]:
            area = sanitize_text(sug.get("area", "Focus Area"))
            desc = sanitize_text(sug.get("description", ""))
            pdf.set_x(10)
            pdf.multi_cell(190, 4.5, f"- [{area}]: {desc}")
            pdf.ln(1)
        for m in evaluation_data.get("missing_topics", [])[:3]:
            if not str(m).startswith("STAR-"):
                pdf.set_x(10)
                pdf.cell(190, 5, sanitize_text(f"- Unaddressed Concept: {m}"), ln=True)
        pdf.ln(4)

        # 6. Question Breakdown
        breakdown = evaluation_data.get("question_breakdown", [])
        if breakdown:
            pdf.set_x(10)
            pdf.set_font("Helvetica", "B", 11)
            pdf.cell(190, 7, "Question-by-Question Deep Dive Assessment", ln=True)
            pdf.set_font("Helvetica", "", 9)

            for idx, q_res in enumerate(breakdown[:5], start=1):
                pdf.set_x(10)
                pdf.set_font("Helvetica", "B", 9)
                q_cat = sanitize_text(q_res.get('category', field_name))
                pdf.cell(190, 5, f"Q{idx} ({q_cat}) - Score: {q_res.get('score', 0)}/100", ln=True)
                
                raw_q_text = q_res.get('question_text', 'Assessment Question')
                q_text = sanitize_text(raw_q_text[:90] + "..." if len(raw_q_text) > 90 else raw_q_text)
                pdf.set_x(10)
                pdf.set_font("Helvetica", "I", 8.5)
                pdf.multi_cell(190, 4, f"Prompt: {q_text}")
                
                raw_fb = q_res.get('feedback', '') or q_res.get('explanation', '')
                feedback_text = sanitize_text(raw_fb)
                pdf.set_x(10)
                pdf.set_font("Helvetica", "", 8.5)
                pdf.multi_cell(190, 4, f"Feedback: {feedback_text}")
                pdf.ln(2)

        os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
        pdf.output(output_path)
        return output_path
